export const ADD_WIDGET_USER_HISTORY = 'ADD_WIDGET_USER_HISTORY';
export const DELETE_WIDGET_USER_HISTORY = 'DELETE_WIDGET_USER_HISTORY';

export const CALCULATE_USER_HISTORY = 'CALCULATE_USER_HISTORY';

export const FETCH_WIDGETS_DB = 'FETCH_WIDGETS_DB';